services:
  - type: web
    name: m-gpt-api
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn mgpt:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: GEMINI_API_KEY
        sync: false
