# render.yaml  (only the startCommand line changes)
services:
  - type: web
    name: m-gpt-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install torch==2.0.1+cpu torchvision==0.15.2+cpu \
                  --find-links https://download.pytorch.org/whl/cpu
      pip install -r requirements.txt
    startCommand: uvicorn mgpt:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
