# render.yaml  (only the startCommand line changes)
services:
  - type: web
    name: m-gpt-api
    runtime: python
    region: oregon            # choose your preferred Render region
    plan: free                # or "starter", "standard", etc.
    branch: main              # branch Render should track
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn mgpt:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: GEMINI_API_KEY   # add the key in Render dashboard; keeps secret out of code
        sync: false
