services:
  - type: web
    name: m-gpt-api
    env: python
    buildCommand: |
      pip install --upgrade pip
      # Install CPU-only PyTorch wheel
      pip install torch==2.0.1+cpu torchvision==0.15.2+cpu --find-links https://download.pytorch.org/whl/cpu
      # Install other dependencies
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn m-gpt:app --host=0.0.0.0 --port=$PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false
